//USER actions

//DEVICE actions

//PREDATOR DATA actions

//UNIVERSAL actions
export const INIT = 'INIT'
export const ERROR = 'ERROR'
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const UPDATE_REGISTRATION_DATA = 'UPDATE_REGISTRATION_DATA'
export const UPDATE_LOGIN_DETAILS = 'UPDATE_LOGIN_DETAILS'
export const STORE_USER_DETAILS = 'STORE_USER_DETAILS'
