//USER actions

//DEVICE actions

//PREDATOR DATA actions

//UNIVERSAL actions
export const INIT = 'INIT'
export const ERROR = 'ERROR'
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const UPDATE_REGISTRATION_DATA = 'UPDATE_REGISTRATION_DATA'
export const UPDATE_LOGIN_DETAILS = 'UPDATE_LOGIN_DETAILS'
export const STORE_USER_DETAILS = 'STORE_USER_DETAILS'
export const STORE_DEVICE_DATA = 'STORE_DEVICE_DATA'
export const UPDATE_PREDATOR_INPUT = 'UPDATE_PREDATOR_INPUT'
export const UPDATE_DEVICE_INPUT = 'UPDATE_DEVICE_INPUT'
export const TOGGLE_SELECTED = 'TOGGLE_SELECTED'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'
export const TOGGLE_AUTHENTICATED = 'TOGGLE_AUTHENTICATED'
export const CLEAR_STATE = 'CLEAR_STATE'
export const TOGGLE_ADD_DEVICE = 'TOGGLE_ADD_DEVICE'
